### ISSUE TITLE
support matplotlib ?

### ISSUE THREAD

**Issue by mrisney** [nalgeon/codapi#1]
```python
import matplotlib.pyplot as plt
import numpy as np

# Create a figure and a set of subplots
fig, axs = plt.subplots(3, 3)

# Generate some random data
data = np.random.rand(3, 3)

# Plot the data on each subplot
for i in range(3):
    for j in range(3):
        axs[i, j].plot(data[i, :], data[j, :])

# Add a grid to each subplot
for ax in axs.flat:
    ax.grid(True)

# Show the plot
plt.show()
```

Gets the following errors : 

```
Traceback (most recent call last):
  File "/sandbox/main.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
 (exit status 1)
```

**Comment by nalgeon** [comment]
You can [add your own sandbox](https://github.com/nalgeon/codapi/blob/main/docs/add-sandbox.md) with `matplotlib` or any other Python package. However, the [widget](https://github.com/nalgeon/codapi-js) does not currently support displaying images. I'll probably look into this in a future release.

**Comment by turntable-justin** [comment]
Any chance codapi would support this or even more interactive elements (e.g. altair charts) anytime soon? Would be super useful for my current project.
