### ISSUE TITLE
I have self-hosted the service, but I still get 403 - Forbidden

### ISSUE THREAD

**Issue by jaronnie** [nalgeon/codapi#12]
I hava self-hosted the service, but I still get 403 - Forbidden on my wordpress blog. Your domain is probably not allowed on Codapi. What should I do next?

````
```python
def greet(name):
  print(f"Hello, {name}!")

greet("World")
```

<codapi-snippet sandbox="python" editor="basic"></codapi-snippet>
<link rel="stylesheet" href="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.css" />
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.js"></script>
````

```shell
root@iZbp13y80xusaram14psd0Z:/opt/codapi# curl -H "content-type: application/json" -d '{ "sandbox": "sh", "command": "run", "files": {"": "echo hello" }}' http://localhost:1313/v1/exec
{"id":"sh_run_16572a32","ok":true,"duration":2091,"stdout":"hello","stderr":""}
```

```shell
root@iZbp13y80xusaram14psd0Z:/opt/codapi# ls
codapi                           codapi.log  images
codapi_0.8.0_linux_amd64.tar.gz  configs     LICENSE
root@iZbp13y80xusaram14psd0Z:/opt/codapi#
```

**Comment by nalgeon** [comment]
I'm afraid it's not very easy.

You also need to expose the Codapi server on your subdomain (e.g. `codapi.example.org`) and setup HTTPS for it. Use your web server (e.g., nginx) to do this.

Then use the [codapi-settings](https://github.com/nalgeon/codapi-js/blob/main/docs/html.md#global-settings) to point the widget to your public Codapi server like this:
```
<codapi-settings url="https://codapi.example.org/v1">
</codapi-settings>
```

**Comment by jaronnie** [comment]
It works well. Thank you!

https://blog.jaronnie.com/test-self-hosting-codapi/

code is:

```markdown
<pre>
echo hello
</pre>

<codapi-snippet sandbox="sh" editor="basic"></codapi-snippet>
<codapi-settings url="https://codapi.api.web.jaronnie.com/v1">
</codapi-settings>
<link rel="stylesheet" href="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.css" />
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.js"></script>
```

Notes:
* If your website is using https. You must set your self-hosting codapi's scheme **https**
![SharedScreenshot](https://github.com/nalgeon/codapi/assets/77253497/5a90edb7-2e8a-4d9f-9746-fe5b71872e5a)

**Comment by nalgeon** [comment]
Great! I'm glad you figured it all out.
