### ISSUE TITLE
HelloStar 计划（HelloStar Plan)

### ISSUE THREAD

**Issue by 521xueweihan** [nalgeon/codapi#13]
Hello, I am the initiator of [HelloGitHub project](https://github.com/521xueweihan/HelloGitHub).

"HelloStar Plan" is a Star growth plan for individual developers. I will use HelloGitHub's traffic (400,000 fans on the entire network) without reservation to help individual developers' open source projects and complete the cold drive phase of the project. Just for making friends and open source, I hope that after your project takes off, you can remember to have HelloGitHub as a friend on your open source road. Those who work hard on open source should be honored and become open source stars.

Requirements are as follows:

1. Individual developer, loves open source
2. Open source project Star < 1k, continuous maintenance for more than 3 months and plans to maintain it for a long time
3. HelloGitHub fans

I plan to help 100 individual open source authors this year, including but not limited to providing help in promotion, operations, and contributions. As long as you treat me as a friend, everything will make sense. If you are interested, bring your open source project and come to me! WeChat: xueweihan (note: 100)

- [codapi](https://hellogithub.com/repository/a369c42f32be4f09950518d57803211c)
- [HelloGitHub](https://github.com/521xueweihan/HelloGitHub/blob/master/content/HelloGitHub96.md#go-%E9%A1%B9%E7%9B%AE)

**Comment by nalgeon** [comment]
Hi, thanks for your interest in Codapi! Not sure what steps are the expected from me here, though.

**Comment by Zxilly** [comment]
Frankly, such a promotion looks more like an annoyance, especially considering that the HelloGitHub website still only supports Chinese.

**Comment by 521xueweihan** [comment]
@nalgeon We invite you to consider joining the [HelloGitHub Badge Program](https://hellogithub.com/en/repository/a369c42f32be4f09950518d57803211c/embed) as a way to further engage with the community and enhance your project's presence. It's completely up to you, and we respect your decision either way.

Thank you for being part of this journey with us.

Warm regards,
The HelloGitHub Team
