### ISSUE TITLE
Help me setup mysql sandbox

### ISSUE THREAD

**Issue by axy1976** [nalgeon/codapi#16]
I have tried using step by step process written in add-sandbox.md file, but it's not working. Please guide me on how can I clean setup the MySQL sandbox on the system.

When using sh command API
```sh
curl -H "content-type: application/json" -d '{ "sandbox": "sh", "command": "run", "files": {"": "echo hello" }}' http://localhost:1313/v1/exec
```
 the output is
```
{
    "id": "sh_run_dd27ed27",
    "ok": true,
    "duration": 650,
    "stdout": "hello\n",
    "stderr": ""
}
```

**Comment by nalgeon** [comment]
Setting up DBMS sandboxes is more involved than programming languages or tools. I'm not ready to provide support on this at this time, sorry.
