### ISSUE TITLE
Donation option?

### ISSUE THREAD

**Issue by mtlynch** [nalgeon/codapi#18]
I see that there's a commercial license option for $500/yr, but is there any lower tier for individual users who don't have a product that uses codapi yet, but they think it's neat and has potential?

**Comment by nalgeon** [comment]
Thank you, Michael! I'm really glad to hear that you find Codapi neat :) Sure, the $500/year is not meant for individual users.

The best way to support Codapi as an individual is to spread the word. Word of mouth is basically the only way people can find out about the project, so it can be a big deal!
