### ISSUE TITLE
run in k8s

### ISSUE THREAD

**Issue by srenatus** [nalgeon/codapi#19]
Heya!

Considering the actual deployment of codapi to run our sandboxes, we've come to the conclusion that all is shiny if codapi is run on a VM, with access to a docker daemon (same machine or not). That's fine, and it's likely the way to go, but I'm also wondering what it would take to make codapi play nice with running on K8s.

As far as I tried, it works from within a rigged dind (docker-in-docker) container, but that still requires the k8s pod to run in _privileged mode_. Now, it feels weird to require elevated privs just to drop them... So far, I haven't come up with much, though. Do you have any ideas or solved this conundrum before?

Thanks! 🙃

**Comment by nalgeon** [comment]
Unfortunately, I have no idea.

**Comment by nalgeon** [comment]
Closing this as I'm unlikely to tinker with k8s anytime soon.

**Comment by srenatus** [comment]
🔖 https://justine.lol/pledge/ could be an alternative to namespace-based approaches 🤔

**Comment by mateothegreat** [comment]
@nalgeon I can cover this for us in short order, no sweat!

Hollar if ya wanna `/ship-it` matthew@matthewdavis.io 🤜
