### ISSUE TITLE
help in creating a tool sandbox

### ISSUE THREAD

**Issue by pottekkat** [nalgeon/codapi#20]
I'm trying to set up a tool sandbox where the tool would listen on a port, and you can basically configure this tool. Similar to this example on the website: https://codapi.org/try/caddy/

But I'm unable to figure out how to do it. I've looked at the code and tried setting it up, but it does not work. Are there any documents or pointers on creating something like that?

I then tried to set up something basic and then build from there, and I failed. I created a Docker image with HTTPBin and curl and tried doing this:

Dockerfile:

```
FROM kennethreitz/httpbin:latest

RUN adduser --home /sandbox --disabled-password --gecos '' sandbox

RUN apt-get update -y
RUN apt-get install -y curl

USER sandbox
WORKDIR /sandbox
```

boxes.json:

```json
{
    "alpine": {
        "image": "codapi/alpine"
    },
    "python": {
        "image": "codapi/python"
    },
    "network-tools": {
        "image": "codapi/network-tools"
    },
    "httpbin": {
        "image": "codapi/httpbin"
    }
}
```

config.json:

```json
{
    "pool_size": 8,
    "verbose": true,
    "box": {
        "runtime": "runc",
        "cpu": 1,
        "memory": 64,
        "network": "bridge",
        "writable": false,
        "volume": "%s:/sandbox:ro",
        "cap_drop": ["all"],
        "ulimit": ["nofile=96"],
        "nproc": 64
    },
    "step": {
        "user": "sandbox",
        "action": "run",
        "timeout": 5,
        "noutput": 4096
    }
}
```

httpbin.json:

```json
{
    "run": {
        "engine": "docker",
        "entry": "main.sh",
        "steps": [
            {
                "box": "httpbin",
                "command": ["sh", "main.sh"],
                "noutput": 8192
            }
        ]
    }
}
```

I expected this to run the shell command (which will be a curl command) on the HTTPBin container, but the command fails with the error `connect to 127.0.0.1 port 80 failed: Connection refused` (isn't HTTPBin running?). I also tried other permutations of the configurations and tested the Docker image in the VM, but nothing seemed to work.

I'm obviously missing something, so I was wondering if there are examples I can look into.

Thanks.

**Comment by nalgeon** [comment]
Please post the complete configuration, including the `Dockerfile` and `boxes.json`.

**Comment by pottekkat** [comment]
@nalgeon Updated the description to add the complete configuration.

**Comment by nalgeon** [comment]
Roughly speaking, Codapi is just a nice wrapper around Docker. So it always makes sense to figure things out with plain Docker first, and add Codapi later.

What you are doing now is similar to running the following Docker command (I'm omitting most of the arguments):

```shell
docker run --rm codapi/httpbin sh main.sh
```

So you run the `sh` command in the container instead of running httpbin (which is the default command defined in the `kennethreitz/httpbin` image). And since httpbin is not running - it fails.

There are several ways to fix this. The main question is, do you really want to start httpbin from scratch on each request (and why)? Maybe it's better to have it always running, and just make curl calls to it on each request?

**Comment by nalgeon** [comment]
Sure, if you plan to change the state, then the shared instance is not an option. So what you need to do on each call is:

1. Start httpbin.
2. Make a curl request to it.
3. Stop httpbin.

This roughly translates to the following Docker commands:

```shell
docker run --rm --detach --name httpbin codapi/httpbin
docker exec httpbin curl http://localhost/uuid
docker stop httpbin
```

Once you get it working in plain Docker, you can setup Codapi to do the same. See the [0.8.0](https://github.com/nalgeon/codapi/releases/0.8.0) release notes for details.

**Comment by pottekkat** [comment]
Thank you. I tried it in my Docker setup and it works but it fails when doing through Codapi 🤔 

These are my updated configurations:

Dockerfile:

```
FROM kennethreitz/httpbin:latest

RUN adduser --home /sandbox --disabled-password --gecos '' sandbox

RUN apt-get update -y
RUN apt-get install -y curl

USER sandbox
WORKDIR /sandbox

CMD ["gunicorn", "-b", "0.0.0.0:80", "httpbin:app", "-k", "gevent"]
```

I followed the release notes and updated the httpbin.json file.

I tried removing `command` from the `before`step. But still I get the same error.

```json
{
    "run": {
        "engine": "docker",
        "entry": "main.sh",
        "before": {
            "box": "httpbin",
            "action": "run",
            "detach": true,
            "command": ["gunicorn","-b", "0.0.0.0:80", "httpbin:app", "-k", "gevent"]
        },
        "steps": [
            {
                "box": ":name",
                "action": "exec",
                "command": [
                    "sh",
                    "main.sh"
                ],
                "noutput": 8192
            }
        ],
        "after": {
            "box": ":name",
            "action": "stop"
        }
    }
}
```

The config.json file wasn't edited from before:

```json
{
    "pool_size": 8,
    "verbose": true,
    "box": {
        "runtime": "runc",
        "cpu": 1,
        "memory": 64,
        "network": "bridge",
        "writable": false,
        "volume": "%s:/sandbox:ro",
        "cap_drop": ["all"],
        "ulimit": ["nofile=96"],
        "nproc": 64
    },
    "step": {
        "user": "sandbox",
        "action": "run",
        "timeout": 5,
        "noutput": 4096
    }
}
```

I tested it like this (the error still remains unable to connect):

```shell
curl -H "content-type: application/json" -d '{ "sandbox": "httpbin", "command": "run", "files": {"": "curl -v localhost:80/anything/test" }}' http://localhost:1313/v1/exec

{"id":"httpbin_run_7dd98118","ok":false,"duration":914,"stdout":"","stderr":"% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...\n* TCP_NODELAY set\n* connect to 127.0.0.1 port 80 failed: Connection refused\n*   Trying ::1...\n* TCP_NODELAY set\n* Immediate connect fail for ::1: Cannot assign requested address\n*   Trying ::1...\n* TCP_NODELAY set\n* Immediate connect fail for ::1: Cannot assign requested address\n* Failed to connect to localhost port 80: Connection refused\n* Closing connection 0\ncurl: (7) Failed to connect to localhost port 80: Connection refused (exit status 7)"}
```

**Comment by nalgeon** [comment]
If you look at the `codapi.log`, you'll see there the full `docker run` command that was executed. Does it work without errors when you run it from the console (remove the `--detach` so that Docker prints errors to stdout)? Probably not.

**Comment by pottekkat** [comment]
I was able to figure out the issue. But for some reason, curl is not able to connect to httpbin. I will try to figure it out.

I noticed that the value of `box.writable` is not set as default value. See: https://github.com/nalgeon/codapi/blob/main/internal/config/config.go#L116

I believe that was unintended?

**Comment by nalgeon** [comment]
> I noticed that the value of `box.writable` is not set as default value

This is intentional. There is no way to set the default `writable` = `true` by default. Writable containers can be a major security problem, so I don't want people to enable it globally.

**Comment by pottekkat** [comment]
That makes sense. Thanks for clarifying.

I got everything working and I think I figured out how to design sandboxes.

In this example from your blog post, you are running a MySQL server container and a client container perpetually and then the "sandbox" that each user interacts with is a different database in the same server. Is my understanding correct?

```
{
    "engine": "docker",
    "before": {
        "box": "mysql",
        "user": "root",
        "action": "exec",
        "command": ["sh", "/etc/mysql/database-create.sh", ":name"]
    },
    "steps": [
        {
            "box": "mysql-client",
            "stdin": true,
            "command": [
                "mysql",
                "--host",
                "mysql",
                "--user",
                ":name",
                "--database",
                ":name",
                "--table"
            ]
        }
    ],
    "after": {
        "box": "mysql",
        "user": "root",
        "action": "exec",
        "command": ["sh", "/etc/mysql/database-drop.sh", ":name"]
    }
}
```

In the case of the Caddy example:

1. do you always have an instance of Caddy running or 
2. do you create one at the start with the `caddy` command
3. or start a caddy container, run all the dependent commands before running the current command, give a response back to the user, and stop the container? So create a Caddy container on every command  run?

I think the Caddy example is the closest to what I'm trying to achieve and your suggestions would be helpful.

**Comment by nalgeon** [comment]
I hope so :) At least that's the scenario we discussed earlier in this issue.

**Comment by pottekkat** [comment]
Ok. Thank you so much. I think I have enough understanding to build on.

We can close this issue.

**Comment by nalgeon** [comment]
Anytime!

**Comment by pottekkat** [comment]
Just to add, I published two playgrounds:

Apache APISIX Playground: https://navendu.me/playground/apisix/
Nginx Playground: https://navendu.me/playground/nginx/

**Comment by nalgeon** [comment]
Thank you for sharing! I've noticed that nginx playground takes 10-15 seconds to respond. Is it the host machine not being very fast or is it the configuration/codapi issue?

**Comment by pottekkat** [comment]
@nalgeon The host machine isn't fast. I plan to upgrade the CPU after some trial runs.

**Comment by nalgeon** [comment]
Thank you for mentioning Codapi and providing a backlink, it means a lot! I've added the APISIX tutorial to the [showcase](https://codapi.org/showcase/#network).

**Comment by pottekkat** [comment]
> I've added the APISIX tutorial to the [showcase](https://codapi.org/showcase/#network).

Wow, thanks! I will keep improving it!
