### ISSUE TITLE
Consider sandbox security

### ISSUE THREAD

**Issue by JensRoland** [nalgeon/codapi#25]
Any time you allow users to execute arbitrary code on a server, you are entering murky waters security-wise.

I am not qualified to assess the scurity of Codapi, but I recommend watching Daniel Cooper's fantastic talk on breaking out of the Judge0 code execution sandbox: https://www.youtube.com/watch?v=aW-w0c3v7Mw

**Comment by nalgeon** [comment]
The whole point of a sandbox is to execute arbitrary code without affecting the outside environment. Still, no sandbox is unbreakable — hence the "make sure you install Codapi on a separate machine" in the [documentation](https://github.com/nalgeon/codapi/blob/main/docs/install.md).
