### ISSUE TITLE
Support installing go modules

### ISSUE THREAD

**Issue by antonmedv** [nalgeon/codapi#3]
Similar to go.dev/play

PS awesome project! I’d like to use your codapi on expr-lang.org :)

**Comment by nalgeon** [comment]
Anton, thanks for your interest! Do you want me to prepare a dedicated [Expr](https://expr-lang.org/) sandbox so you can use it in the Getting Started guide and other parts of the documentation?

As for [go.dev/play](https://go.dev/play/), I don't think it supports installing modules. Quoting the docs:

> The playground can use most of the standard library, with some exceptions. The only communication a playground program has to the outside world is by writing to standard output and standard error.

Installing arbitrary modules in the sandbox would be too slow (and insecure).

**Comment by antonmedv** [comment]
Here is an example of playground: https://go.dev/play/p/XCoNXEjm3TS
It installs github.com/expr-lang/expr inside it. 

If you could add support for Expr it will be super cool =). I can use it in https://expr-lang.org/docs/language-definition

**Comment by nalgeon** [comment]
> It installs github.com/expr-lang/expr inside it.

Ouch, I was not aware of this feature! Still, I'd rather not allow arbitrary modules (yet).

I'd love to add Expr support, though! In fact, I have already done so (the name of the sandbox is `expr-lang`).

I think you can use this sandbox both for full-blown Go examples (on the Expr Home and Getting Started pages) and for expression evaluation (Language Definition page).

I've prepared some examples:

- [Home page](https://codapi.org/try/expr-lang/)
- [Getting Started](https://codapi.org/try/expr-lang/getting-started/)
- [Language Definition](https://codapi.org/try/expr-lang/language/)

I'd send you a PR, but it seems you're using Docusaurus, and I couldn't find the documentation build config or tasks in the Expr repo to check everything locally (integration with Docusaurus can be tricky sometimes).

**Comment by antonmedv** [comment]
Oh! Awesome! Yes, docusaurus site is in private repo right now. Will try to integrate those today.

**Comment by nalgeon** [comment]
Awesome! Let me know if you have any questions in the process.

As you probably know, Docusaurus' "markdown" is not really markdown (it is handled as a React component).

So it does not play well with web components (which the Codapi widget is) or templates.

Please see this [guide](https://github.com/nalgeon/codapi-js/blob/main/docs/docusaurus.md) for using Codapi with Docusaurus.

If you're testing on localhost, port 3000 is allowed to access Codapi.

**Comment by nalgeon** [comment]
@antonmedv Any luck integrating Codapi? I'm happy to help if you have any questions.

**Comment by antonmedv** [comment]
I was able to integrate it, but I need to figure out a better editor for expr.

**Comment by nalgeon** [comment]
Codejar maybe? It's a perfect fit for interactive examples, IMHO. I use it on the codapi website.

**Comment by nalgeon** [comment]
Okay then. Let me know if you have any questions.
