### ISSUE TITLE
Error - 403 - Forbidden. Your domain is probably not allowed on Codapi.

### ISSUE THREAD

**Issue by upgundecha** [nalgeon/codapi#4]
I installed codeapi on my personal blog. However, when I run the code snippets, I see the below error:

`403 - Forbidden. Your domain is probably not allowed on Codapi.`

<img width="958" alt="image" src="https://github.com/nalgeon/codapi/assets/1009929/aa4ddef8-af1f-4d5b-8c5a-b0d3b5994997">

Do I need a subscription to the codeapi platform in order to run the examples?

**Comment by nalgeon** [comment]
You are using the cloud version and not self-hosting. So you need to be enrolled in the beta program for the playgrounds to work. It looks like you've already applied, so I've enabled unmesh.dev, and now the examples should work fine.

**Comment by upgundecha** [comment]
Thanks, @nalgeon, it worked!
