### ISSUE TITLE
Permission denied on alpine

### ISSUE THREAD

**Issue by muellerj** [nalgeon/codapi#6]
I was trying to get the self-hosted server running Alpine 3.19 to work but ran into problems when accessing the temporary files from the docker image:

~~~ sh
/srv/codapi # cat bin/test
#!/bin/sh

curl \
  -H "content-type: application/json" \
  -d '{ "sandbox": "sh", "command": "run", "files": {"": "echo hello" }}' \
  http://localhost:1313/v1/exec
/srv/codapi # bin/test | jq
{
  "id": "sh_run_b3a94e77",
  "ok": false,
  "duration": 416,
  "stdout": "",
  "stderr": "sh: can't open 'main.sh': Permission denied\n (exit status 2)"
}
~~~

The logs look similar:

~~~ log
/var/lib/codapi # tail -n2 /var/log/codapi/openrc.log 
2024/01/15 22:23:50 [run --rm --name sh_run_b3a94e77 --runtime runc --cpus 1 --memory 64m --network none --pids-limit 64 --user sandbox --read-only --volume /tmp/1851081613:/sandbox:ro --cap-drop all --ulimit nofile=96 codapi/alpine sh main.sh]
2024/01/15 22:23:50 ✗ sh_run_b3a94e77: sh: can't open 'main.sh': Permission denied (exit status 2)
~~~

The folder `/tmp` has the usual permissions.

I've documented my setup [here][1]. Is there something I've misconfigured?

Thanks for your help in advance!

~~~
[1]: https://git.tigger.cloud/public/codapi-setup-alpine
~~~

**Comment by muellerj** [comment]
One more indicator that might help: The file does get created and it looks to me as if it has the correct permissions:

~~~ sh
# Run during a request
/var/lib/codapi # while true; do ls -l /tmp/* | grep codapi; done
-r--r--r--    1 codapi   docker          10 Jan 15 22:48 main.sh
# ...
~~~

**Comment by nalgeon** [comment]
<https://git.tigger.cloud/public/codapi-setup-alpine> - this link requires authorization.

**Comment by muellerj** [comment]
If you'd like, I can mirror the repo on GitHub.

**Comment by nalgeon** [comment]
No, it's fine, thank you. Now I need some time to investigate, probably be back tomorrow.

**Comment by nalgeon** [comment]
Fixed in [0.7.0](https://github.com/nalgeon/codapi/releases/0.7.0), please try the new codapi binary.

**Comment by muellerj** [comment]
Indeed! Thank you very much for the fast response 😄 Please feel free to close this.

**Comment by nalgeon** [comment]
Great! Thanks for reporting the issue.
