### ISSUE TITLE
Possible to use with mintlify?

### ISSUE THREAD

**Issue by turntable-justin** [nalgeon/codapi#9]
Hi Anton,

We recently made the decision to use [mintlify](https://mintlify.com/) instead of Docusaurus, so I am trying to get Codapi set up for our new site. Unfortunately it didn't work after including custom [css](https://mintlify.com/docs/integrations/custom/css) and [js](https://mintlify.com/docs/integrations/custom/js). Any ideas on how to make this work?

Best,
Justin

**Comment by nalgeon** [comment]
No ideas, sorry.

> Custom JS is a feature available on the growth plan.

I'd rather not pay $400 just to test it. I hope you get some kind of support for that money, so I think you can open an issue, describe the symptoms (errors you get, etc.) — and maybe get some help from the Mintlify team.
